language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t kealanmaas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kealanmaas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-React-env"
  bucket_name: "elasticbeanstalk-eu-west-1-348977772231"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"